changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
      - github-actions
  categories:
    - title: New Features
      labels:
        - enhancement
      exclude:
        labels:
          - bug
    - title: Bug Fixes
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"
